branch-defaults:
  default:
    environment: youtube-clone-1-dev
global:
  application_name: youtube-clone-1
  branch: null
  default_ec2_keyname: youtube-instance-login-key
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
